# Harden the PCE with ilo-vpngen - MNC only
- name: Check if we a swan package is installed
  command: rpm -qa | grep swan
  register: swan_check
  when: node_type != "snc0"
  tags:
    - ilo-vpngen
    - hardening

- name: End ansible build if swan package is installed
  meta: end_play
  when:
    - node_type != "snc0"
    - swan_check.rc != 0
  tags:
    - ilo-vpngen
    - hardening

- name: Download libreswan RPM
  get_url:
    url: https://download.libreswan.org/binaries/rhel/7/x86_64/libreswan-3.31-1.el7_7.x86_64.rpm
    dest: /tmp/libreswan-3.31-1.el7_7.x86_64.rpm
  when: node_type != "snc0"
  tags:
    - ilo-vpngen
    - hardening

- name: "Install Libreswan RPM"
  yum:
    name: /tmp/libreswan-3.31-1.el7_7.x86_64.rpm
    state: present
  when: node_type != "snc0"
  tags:
    - ilo-vpngen
    - hardening

- name: Create /var/tmp/illumio-vpngen on each node_type if it does not exist
  file:
    path: /var/tmp/illumio-vpngen
    state: directory
  when: node_type == "core0"
  tags:
    - ilo-vpngen
    - hardening

- name: Copy the ilo-vpngen script to the directory
  copy:
    src: ilo-vpngen
    dest: /var/tmp/illumio-vpngen
    mode: a+x
  when: node_type == "core0"
  tags:
    - ilo-vpngen
    - hardening

- name: Create file with ip addresses
  template:
    src: ip_addrs_input.txt.j2
    dest: /var/tmp/illumio-vpngen/ip_addrs_input.txt
  when: node_type == "core0"
  tags:
    - ilo-vpngen
    - hardening

- name: Execute ilo-vpngen script
  command: ./ilo-vpngen -i ip_addrs_input.txt -o deploy_vpn.sh
  args:
    chdir: /var/tmp/illumio-vpngen/
  when: node_type == "core0"
  tags:
    - ilo-vpngen
    - hardening

- name: Download the deploy_vpn.sh to ansible server
  fetch:
    src: /var/tmp/illumio-vpngen/deploy_vpn.sh
    dest: roles/pce/files/deploy_vpn.sh
    flat: yes
  when: node_type == "core0"
  tags:
    - ilo-vpngen
    - hardening

- name: Send deploy_vpn.sh to all servers
  copy:
    src: deploy_vpn.sh
    dest: /tmp/deploy_vpn.sh
    mode: a+x
  when: node_type != "snc0"
  tags:
    - ilo-vpngen
    - hardening

- name: Make sure packages are installed
  become: yes
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - ldns
      - libevent
      - nss
      - nss-tools
      - unbound-libs
      - libpcap
      - nspr
      - nss-softokn
      - nss-softokn-freebl
      - nss-sysinit
      - nss-util
  when: node_type != "snc0"
  tags:
    - ilo-vpngen
    - hardening

- name: Execute deploy_vpn.sh script
  command: ./deploy_vpn.sh
  when: node_type != "snc0"
  become: yes
  args:
    chdir: /tmp/
  tags:
    - ilo-vpngen
    - hardening

- name: Start IPSec Service on all nodes
  systemd:
    name: ipsec
    enabled: yes
    state: started
  when: node_type != "snc0"
  tags:
    - ilo-vpngen
    - hardening
