- hosts: linux,ansible
  become: true
  roles:
    - role: linux

- hosts: win,member,dc
  roles:
    - role: windows

- hosts: ansible
  tasks:
    - name: Import labels
      shell:
        cmd: ./workloader wkld-import ansible/wkld-labels.csv --update-pce --no-prompt
      args:
        chdir: /home/centos
