# -*- mode: ruby -*-
# vi: set ft=ruby :

# Box settings
Vagrant.configure("2") do |config|

    # Set up the VMware provider
    config.vm.provider "vmware_fusion" do |vmware|
      vmware.vmx["ethernet0.pcislotnumber"] = "32" # Needed for setting up vmware fusion
      vmware.gui = false
      vmware.memory = 4096
      vmware.cpus = 2
    end
  
  # Set up the Virtual Box provider
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = 4096
      vb.cpus = 2
    end
  
    # Use a CentOS 7 base box
    config.vm.box = "bento/ubuntu-16.04"
  
    # Set up shared folder
    config.vm.synced_folder '../../common-shared/', '/vagrant', disabled: false
  
  end