- name: Stop the PCE
  command: /opt/illumio-pce/illumio-pce-ctl stop --wait
  become: yes
  become_user: ilo-pce
  args:
    chdir: /tmp/

- name: Upgrade PCE rpm to all nodes
  yum:
    name: /tmp/{{ ui_rpm | basename }}
    state: present
  when: pce_rpm is defined

- name: Upgrade PCE UI rpm to core and SNC nodes
  yum:
    name: /tmp/{{ ui_rpm | basename }}
    state: present
  when: ui_rpm is defined and node_type in ['core0', 'core1', 'snc0']
