---
- name: Change hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname_short }}"
  become: true

- name: Install nmap and tcpdump
  become: true
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - nmap
      - tcpdump
