---
- name: Change hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname_short }}"
  become: true

- name: Install nmap, tcpdump, and bzip2
  become: true
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - nmap
      - tcpdump
      - bzip2
