# Move Linux VEN to hosts
- name: Linux - copy the VEN RPM to the remote hosts
  copy:
    src: ../ven/illumio-ven-19.3.0-6104.c{{ ansible_distribution_major_version }}.x86_64.rpm
    dest: /tmp/ven.rpm
  tags:
    - never
    - venpackage

- name: Linux - install the VEN RPM
  become: true
  become_user: root
  yum:
    name: /tmp/ven.rpm
  tags:
    - never
    - venpackage

- name: Linux - activate the VEN
  become: true
  become_user: root
  shell:
    cmd: /opt/illumio_ven/illumio-ven-ctl activate --management-server p-lab.poc.segmentationpov.com:8443 --activation-code "{{ pairing_key }}"
  tags:
    - never
    - venpackage
