---
- hosts: linux
  become: true
  roles:
    - role: linux
  tags:
    - linux-base
  ignore_errors: yes

- hosts: win
  gather_facts: True
  roles:
    - role: windows
  tags:
    - windows-base
  ignore_errors: yes

- hosts: dc
  gather_facts: True
  roles:
    - role: windows
    - role: dc
  tags:
    - dc
  ignore_errors: yes

- hosts: member
  gather_facts: True
  roles:
    - role: windows
    - role: member
  tags:
    - member
  ignore_errors: yes

- hosts: promoted_dc
  gather_facts: True
  roles:
    - role: promoted_dc
  tags:
    - promoted_dc
  ignore_errors: yes
