# Unpair the VEN and uninstall the VEN software
- name: Unpair VEN and uninstall software
  win_shell: .\illumio-ven-ctl.ps1 unpair saved
  args:
    chdir: C:\Program Files\Illumio
    removes: C:\Program Files\Illumio\illumio-ven-ctl.ps1

# Find the MSI
- name: Find the Illumio MSI
  win_find:
    paths: C:\Users\Administrator
    patterns: illumio-ven-*.msi
  register: illumio_vens

# Remove the VEN MSI
- name: Remove MSI
  win_file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ illumio_vens.files }}"
