# -*- mode: ruby -*-
# vi: set ft=ruby :

# Brings up a CentOS machine with ilo-cli installed

# Box settings
Vagrant.configure("2") do |config|

    # Set up the VirtualBox
    config.vm.provider "vmware_fusion" do |vm|
      vm.gui = false
      vm.memory = 1024
      vm.cpus = 1
      vm.vmx["ethernet0.pcislotnumber"] = "32"
    end
  
    # Use a CentOS 7 base box
    config.vm.box = "centos/7"
  
    # Set up shared folder
    config.vm.synced_folder 'shared/', '/vagrant', disabled: false

    # Install ilo-cli
    config.vm.provision "shell", inline: "rpm -iv /vagrant/illumio-pce-cli-*.rpm", privileged: true
    
  end
