# Copy, install, and activate VEN on all Windows boxes
- name: Copy the VEN MSI to the remote hosts
  win_copy:
    src: ../ven/VENInstaller-19.3.0-6104-x64.msi
    dest: C:\Users\Administrator\windows-ven.msi
  tags:
    - never
    - venpackage

- name: Install the VEN MSI
  win_package:
    path: C:\Users\Administrator\windows-ven.msi
  tags:
    - never
    - venpackage

- name: Activate the VEN
  win_shell: .\illumio-ven-ctl.ps1 activate -management-server p-lab.poc.segmentationpov.com:8443 -activation-code "{{ pairing_key }}"
  args:
    chdir: C:\Program Files\Illumio
  tags:
    - never
    - venpackage
