---
- name: Remove existing machine cert with poc.segmentationpov.com if it exists
  win_shell: |
    $thumbprint= (Get-ChildItem -Path Cert:\LocalMachine\My | Where-Object {$_.Subject -match "poc.segmentationpov.com"}).Thumbprint;
    if (-not ([string]::IsNullOrEmpty($thumbprint)))
    {
      Remove-Item -Path cert:\LocalMachine\My\$thumbprint -DeleteKey
    }
  tags:
    - remove

- name: Remove existing ca cert with poc.segmentationpov.com if it exists
  win_shell: |
    $thumbprint= (Get-ChildItem -Path Cert:\LocalMachine\Root | Where-Object {$_.Subject -match "poc.segmentationpov.com"}).Thumbprint;
    if (-not ([string]::IsNullOrEmpty($thumbprint)))
    {
      Remove-Item -Path cert:\LocalMachine\Root\$thumbprint -DeleteKey
    }
  tags:
    - remove

- name: Move the machine pk12 file
  win_copy:
    src: "{{ inventory_hostname }}.p12"
    dest: C:\
  tags:
    - add

- name: Move the CA cert file
  win_copy:
    src: ca.crt
    dest: C:\
  tags:
    - add

- name: Add machine cert to personal cert store
  win_shell: |
    Import-PfxCertificate -FilePath "C:\{{ inventory_hostname }}.p12" -CertStoreLocation cert:\LocalMachine\My
  tags:
    - add

- name: Add CA Trust Root
  win_shell: |
    Import-Certificate -FilePath "C:\ca.crt" -CertStoreLocation cert:\LocalMachine\Root
  tags:
    - add
