# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # Set up the VMware Fusion provider
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = 4096
    end
  
    # Use a Ubuntu base box
    config.vm.box = "fla_torres/solaris-11_3"
  
    # Set up shared folder
    config.vm.synced_folder '../common-shared/', '/vagrant', disabled: false
  
  end
  
